package com.omni.downloader.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

data class AppStrings(
    // 底部导航栏
    val navHome: String,
    val navTasks: String,
    val navSettings: String,

    // 首页
    val appSubtitle: String,
    val inputPlaceholder: String,
    val clear: String,
    val paste: String,
    val pasteClipboard: String,
    val startAnalyze: String,
    val analyzing: String,
    val activeTasksTitle: String,
    val viewAll: String,
    val analyzeFailedTitle: String,
    val proxyTip: String,
    val copyErrorLog: String,
    val errorLogCopied: String,
    val setProxy: String,

    // 任务页
    val tasksTitle: String,
    val tabDownloading: String,
    val tabCompleted: String,
    val emptyDownloading: String,
    val emptyCompleted: String,
    val clearCompleted: String,
    val openFolder: String,
    val play: String,
    val retry: String,
    val delete: String,
    val cancel: String,

    // 设置页
    val settingsTitle: String,
    val languageSection: String,
    val languageZhCn: String,
    val languageZhTw: String,
    val languageEn: String,
    val languageJa: String,
    val proxySection: String,
    val proxyHint: String,
    val proxyPlaceholder: String,
    val applyProxy: String,
    val clearProxy: String,
    val proxySaved: String,
    val proxyCleared: String,
    val storageSection: String,
    val customPathHint: String,
    val defaultPath: String,
    val pathPlaceholder: String,
    val chooseFolder: String,
    val resetDefault: String,
    val pathSaved: String,
    val pathReset: String,
    val engineSection: String,
    val updateEngine: String,
    val updating: String,
    val engineHint: String,
    val appInfoSection: String,
    val appVersion: String,

    // 解析配置面板
    val formatSheetTitle: String,
    val mediaSelection: String,
    val downloadType: String,
    val typeVideo: String,
    val typeAudio: String,
    val resolution: String,
    val audioFormat: String,
    val startDownload: String,
    val downloadAll: String,
    val gifHint: String,
    val typeCover: String,
    val saveCover: String,
    val saveCoverSuccess: String,
    val coverDescription: String,
    val downloadSingleMode: String,
    val downloadCollectionMode: String,
    val selectAll: String,
    val deselectAll: String,
    val invertSelection: String,
    val selectedEpisodesCount: String,
    val downloadSelected: String,
    val pleaseSelectEpisode: String,

    // 模式切换 Tab（音画合流、纯画面、音频、动图）
    val tabVideo: String,
    val tabVideoSub: String,
    val tabMute: String,
    val tabMuteSub: String,
    val tabAudio: String,
    val tabAudioSub: String,
    val tabGif: String,
    val tabGifSub: String,

    // 附加封面选项
    val attachedCoverTitle: String,
    val attachedCoverDesc: String,
    val saveCoverAction: String,

    // 画质与音频选择提示
    val selectResolutionWithAudio: String,
    val selectResolutionMute: String,
    val selectAudioFormat: String,
    val gifEngineTitle: String,
    val gifEngineDesc: String,
    val switchMultiVideoPrompt: String,
    val switchBilibiliPartPrompt: String,
    val videoPartLabel: String,
    val batchDownloadAudio: String,
    val batchDownloadGif: String,
    val batchDownloadVideos: String,
    val downloadAllCount: String,
    val switchToCollectionMode: String,

    // 设置与存储扩展
    val engineStatusTitle: String,
    val engineStatusRunning: String,
    val engineStatusNotReady: String,
    val storageCleanTitle: String,
    val cleanCacheAction: String,
    val cleanCacheSuccess: String,
    val customBadge: String,
    val changeFolderDialogTitle: String,
    val changeFolderDialogHint: String,
    val selectViaFilePicker: String,
    val commonFolders: String,
    val folderDefault: String,
    val folderMovies: String,
    val folderMusic: String,
    val pathInputLabel: String,
    val saveSettings: String,

    // 任务状态与徽章
    val statusPending: String,
    val statusDownloading: String,
    val statusProcessing: String,
    val statusCompleted: String,
    val statusFailed: String,
    val statusCancelled: String,
    val badgeVideo: String,
    val badgeMute: String,
    val badgeAudio: String,
    val badgeGif: String,
    val badgeCover: String
)

val ZhHansStrings = AppStrings(
    navHome = "首页",
    navTasks = "任务",
    navSettings = "设置",

    appSubtitle = "支持 哔哩哔哩、抖音、快手、小红书、YouTube、TikTok、X 等 10 大主流平台",
    inputPlaceholder = "粘贴视频链接或分享文本...",
    clear = "清除",
    paste = "粘贴",
    pasteClipboard = "粘贴剪贴板",
    startAnalyze = "立即解析",
    analyzing = "解析中...",
    activeTasksTitle = "正在下载的任务",
    viewAll = "查看全部",
    analyzeFailedTitle = "解析未能成功",
    proxyTip = "提示: 解析 YouTube / X 需配合科学上网；如已开启代理，可在设置中配置代理端口。",
    copyErrorLog = "复制错误日志",
    errorLogCopied = "已复制错误日志",
    setProxy = "设置代理",

    tasksTitle = "下载管理",
    tabDownloading = "下载中",
    tabCompleted = "已完成",
    emptyDownloading = "暂无正在进行的下载任务",
    emptyCompleted = "暂无已完成的下载记录",
    clearCompleted = "清空记录",
    openFolder = "打开文件夹",
    play = "播放",
    retry = "重试",
    delete = "删除",
    cancel = "取消",

    settingsTitle = "偏好设置",
    languageSection = "语言 (Language)",
    languageZhCn = "简体中文",
    languageZhTw = "繁體中文",
    languageEn = "English",
    languageJa = "日本語",
    proxySection = "网络代理设置 (Proxy)",
    proxyHint = "支持 HTTP / SOCKS5 代理",
    proxyPlaceholder = "",
    applyProxy = "保存并应用",
    clearProxy = "清空代理",
    proxySaved = "代理已更新",
    proxyCleared = "代理已清空",
    storageSection = "存储目录设置",
    customPathHint = "自定义下载路径：",
    defaultPath = "默认 (公共 Download/OmniDownloader)",
    pathPlaceholder = "留空恢复默认公共存储目录",
    chooseFolder = "选择文件夹",
    resetDefault = "恢复默认",
    pathSaved = "保存路径已更新",
    pathReset = "已恢复默认保存路径",
    engineSection = "核心引擎组件",
    updateEngine = "在线更新核心解析库",
    updating = "更新中...",
    engineHint = "拉取最新 yt-dlp 解析规则",
    appInfoSection = "应用信息",
    appVersion = "版本",

    formatSheetTitle = "下载配置",
    mediaSelection = "选择多媒体片段",
    downloadType = "下载模式",
    typeVideo = "完整视频 (包含音轨)",
    typeAudio = "纯音频 (MP3/M4A)",
    resolution = "视频画质",
    audioFormat = "音频编码格式",
    startDownload = "开始下载",
    downloadAll = "全部下载",
    gifHint = "已智能识别为动态图/短动效，可作为高画质视频下载",
    typeCover = "保存封面",
    saveCover = "保存封面",
    saveCoverSuccess = "封面已保存至相册",
    coverDescription = "原图高清封面，直接保存至系统相册",
    downloadSingleMode = "下载单集",
    downloadCollectionMode = "下载合集",
    selectAll = "全选",
    deselectAll = "取消全选",
    invertSelection = "反选",
    selectedEpisodesCount = "已选 %d / %d 集",
    downloadSelected = "下载所选",
    pleaseSelectEpisode = "请至少勾选一个视频",

    tabVideo = "音画合流",
    tabVideoSub = "高清音画",
    tabMute = "纯画面",
    tabMuteSub = "无声素材",
    tabAudio = "提取音频",
    tabAudioSub = "MP3 / M4A",
    tabGif = "动态图",
    tabGifSub = "循环动效",

    attachedCoverTitle = "附加选项：视频原画封面",
    attachedCoverDesc = "提取发布者高清原图，直接存入系统相册",
    saveCoverAction = "存入相册",

    selectResolutionWithAudio = "选择视频分辨率 (自动合成最佳声音)",
    selectResolutionMute = "选择纯视频分辨率 (完全去除声音轨，静音素材)",
    selectAudioFormat = "选择导出的音频格式",
    gifEngineTitle = "高保真 GIF 动图转换",
    gifEngineDesc = "• 内置 FFmpeg 双 Pass 调色板引擎，还原细腻生动色彩与紧凑体积\n• 导出为标准 .gif 格式，微信、相册、QQ 无需播放器即可直接开播与转发\n• 如需保存原画视频文件，可随时切换回「音画合流」下载为 MP4",
    switchMultiVideoPrompt = "点击切换当前预览与独立下载的视频:",
    switchBilibiliPartPrompt = "点击切换当前预览与下载的分P/分集:",
    videoPartLabel = "视频 %d",
    batchDownloadAudio = "下载所选音频 (%d 首 · %s)",
    batchDownloadGif = "下载所选动图 (%d 个)",
    batchDownloadVideos = "下载所选合集 (%d 集 · %s)",
    downloadAllCount = "全部下载 (%d 集)",
    switchToCollectionMode = "切换为合集多选下载 (%d 集)",

    engineStatusTitle = "核心引擎状态",
    engineStatusRunning = "正常运行",
    engineStatusNotReady = "未就绪",
    storageCleanTitle = "存储瘦身与数据清理",
    cleanCacheAction = "一键清理历史运行缓存",
    cleanCacheSuccess = "历史缓存已清理完毕，存储空间已释放",
    customBadge = "自定义",
    changeFolderDialogTitle = "更改下载保存目录",
    changeFolderDialogHint = "选择快捷预设或使用系统文件选择器：",
    selectViaFilePicker = "系统文件管理器中选取文件夹",
    commonFolders = "快捷常用目录:",
    folderDefault = "默认下载",
    folderMovies = "影视库",
    folderMusic = "音乐库",
    pathInputLabel = "存储绝对路径",
    saveSettings = "保存设置",

    statusPending = "等待中",
    statusDownloading = "正在下载",
    statusProcessing = "正在合并",
    statusCompleted = "已完成",
    statusFailed = "失败",
    statusCancelled = "已取消",
    badgeVideo = "完整",
    badgeMute = "纯画面",
    badgeAudio = "音频",
    badgeGif = "动图",
    badgeCover = "封面"
)

val ZhHantStrings = AppStrings(
    navHome = "首頁",
    navTasks = "任務",
    navSettings = "設定",

    appSubtitle = "支援 嗶哩嗶哩、抖音、快手、小紅書、YouTube、TikTok、X 等 10 大主流平台",
    inputPlaceholder = "貼上影片連結或分享文字...",
    clear = "清除",
    paste = "貼上",
    pasteClipboard = "貼上剪貼簿",
    startAnalyze = "立即解析",
    analyzing = "解析中...",
    activeTasksTitle = "正在下載的任務",
    viewAll = "查看全部",
    analyzeFailedTitle = "解析未能成功",
    proxyTip = "提示: 解析 YouTube / X 需配合代理連線；如已開啟代理，可在設定中配置代理埠。",
    copyErrorLog = "複製錯誤記錄",
    errorLogCopied = "已複製錯誤記錄",
    setProxy = "設定代理",

    tasksTitle = "下載管理",
    tabDownloading = "下載中",
    tabCompleted = "已完成",
    emptyDownloading = "暫無進行中的下載任務",
    emptyCompleted = "暫無已完成的下載記錄",
    clearCompleted = "清空記錄",
    openFolder = "開啟資料夾",
    play = "播放",
    retry = "重試",
    delete = "刪除",
    cancel = "取消",

    settingsTitle = "偏好設定",
    languageSection = "語言 (Language)",
    languageZhCn = "简体中文",
    languageZhTw = "繁體中文",
    languageEn = "English",
    languageJa = "日本語",
    proxySection = "網路代理設定 (Proxy)",
    proxyHint = "支援 HTTP / SOCKS5 代理",
    proxyPlaceholder = "",
    applyProxy = "儲存並套用",
    clearProxy = "清空代理",
    proxySaved = "代理已更新",
    proxyCleared = "代理已清空",
    storageSection = "儲存目錄設定",
    customPathHint = "自訂下載路徑：",
    defaultPath = "預設 (公共 Download/OmniDownloader)",
    pathPlaceholder = "留空恢復預設儲存目錄",
    chooseFolder = "選取資料夾",
    resetDefault = "恢復預設",
    pathSaved = "儲存路徑已更新",
    pathReset = "已恢復預設儲存路徑",
    engineSection = "核心引擎組件",
    updateEngine = "線上更新核心解析庫",
    updating = "更新中...",
    engineHint = "獲取最新 yt-dlp 解析規則",
    appInfoSection = "應用程式資訊",
    appVersion = "版本",

    formatSheetTitle = "下載設定",
    mediaSelection = "選取多媒體項目",
    downloadType = "下載模式",
    typeVideo = "完整影片 (包含音訊)",
    typeAudio = "僅音訊 (MP3/M4A)",
    resolution = "影片畫質",
    audioFormat = "音訊編碼格式",
    startDownload = "開始下載",
    downloadAll = "全部下載",
    gifHint = "已智慧辨識為動態圖/短動效，可作為高畫質影片下載",
    typeCover = "儲存封面",
    saveCover = "儲存封面",
    saveCoverSuccess = "封面已儲存至相簿",
    coverDescription = "原圖高清封面，直接儲存至系統相簿",
    downloadSingleMode = "下載單集",
    downloadCollectionMode = "下載合集",
    selectAll = "全選",
    deselectAll = "取消全選",
    invertSelection = "反選",
    selectedEpisodesCount = "已選 %d / %d 集",
    downloadSelected = "下載所選",
    pleaseSelectEpisode = "請至少勾選一個影片",

    tabVideo = "完整影片",
    tabVideoSub = "高畫質音畫",
    tabMute = "純畫面",
    tabMuteSub = "無聲素材",
    tabAudio = "擷取音訊",
    tabAudioSub = "MP3 / M4A",
    tabGif = "動態圖",
    tabGifSub = "循環動效",

    attachedCoverTitle = "附加選項：影片原圖封面",
    attachedCoverDesc = "擷取發布者高畫質原圖，直接儲存至系統相簿",
    saveCoverAction = "存入相簿",

    selectResolutionWithAudio = "選取影片解析度 (自動合併最佳音訊)",
    selectResolutionMute = "選取純影片解析度 (完全去除聲音軌，靜音素材)",
    selectAudioFormat = "選取導出的音訊格式",
    gifEngineTitle = "高保真 GIF 動圖轉換",
    gifEngineDesc = "• 內建 FFmpeg 雙 Pass 調色盤引擎，還原細膩生動色彩與緊湊體積\n• 匯出為標準 .gif 格式，通訊軟體與相簿可直接播放\n• 如需儲存原畫影片，可隨時切換回「完整影片」下載為 MP4",
    switchMultiVideoPrompt = "點擊切換當前預覽與獨立下載的影片:",
    switchBilibiliPartPrompt = "點擊切換當前預覽與下載的分P/分集:",
    videoPartLabel = "影片 %d",
    batchDownloadAudio = "下載所選音訊 (%d 首 · %s)",
    batchDownloadGif = "下載所選動圖 (%d 個)",
    batchDownloadVideos = "下載所選合集 (%d 集 · %s)",
    downloadAllCount = "全部下載 (%d 集)",
    switchToCollectionMode = "切換為合集多選下載 (%d 集)",

    engineStatusTitle = "核心引擎狀態",
    engineStatusRunning = "正常運作",
    engineStatusNotReady = "未就緒",
    storageCleanTitle = "儲存瘦身與資料清理",
    cleanCacheAction = "一鍵清理歷史快取",
    cleanCacheSuccess = "歷史快取已清理完畢，儲存空間已釋放",
    customBadge = "自訂",
    changeFolderDialogTitle = "更改下載儲存目錄",
    changeFolderDialogHint = "選取快捷預設或使用系統檔案選擇器：",
    selectViaFilePicker = "系統檔案管理器中選取資料夾",
    commonFolders = "快捷常用目錄:",
    folderDefault = "預設下載",
    folderMovies = "影視庫",
    folderMusic = "音樂庫",
    pathInputLabel = "儲存絕對路徑",
    saveSettings = "儲存設定",

    statusPending = "等待中",
    statusDownloading = "正在下載",
    statusProcessing = "正在合併",
    statusCompleted = "已完成",
    statusFailed = "失敗",
    statusCancelled = "已取消",
    badgeVideo = "完整",
    badgeMute = "純畫面",
    badgeAudio = "音訊",
    badgeGif = "動圖",
    badgeCover = "封面"
)

val EnStrings = AppStrings(
    navHome = "Home",
    navTasks = "Tasks",
    navSettings = "Settings",

    appSubtitle = "Fast downloads for Bilibili, TikTok, Douyin, X, YouTube & 10+ platforms",
    inputPlaceholder = "Paste video link or shared text...",
    clear = "Clear",
    paste = "Paste",
    pasteClipboard = "Paste Clipboard",
    startAnalyze = "Analyze",
    analyzing = "Analyzing...",
    activeTasksTitle = "Active Downloads",
    viewAll = "View All",
    analyzeFailedTitle = "Analysis Failed",
    proxyTip = "Tip: Accessing YouTube/X may require a proxy. You can configure proxy port in Settings.",
    copyErrorLog = "Copy Error Log",
    errorLogCopied = "Error log copied to clipboard",
    setProxy = "Set Proxy",

    tasksTitle = "Downloads",
    tabDownloading = "Downloading",
    tabCompleted = "Completed",
    emptyDownloading = "No active download tasks",
    emptyCompleted = "No completed downloads yet",
    clearCompleted = "Clear History",
    openFolder = "Open Folder",
    play = "Play",
    retry = "Retry",
    delete = "Delete",
    cancel = "Cancel",

    settingsTitle = "Settings",
    languageSection = "Language",
    languageZhCn = "简体中文",
    languageZhTw = "繁體中文",
    languageEn = "English",
    languageJa = "日本語",
    proxySection = "Network Proxy",
    proxyHint = "Supports HTTP and SOCKS5 proxies",
    proxyPlaceholder = "",
    applyProxy = "Save & Apply",
    clearProxy = "Clear Proxy",
    proxySaved = "Proxy updated",
    proxyCleared = "Proxy cleared",
    storageSection = "Storage Location",
    customPathHint = "Custom Download Path:",
    defaultPath = "Default (Download/OmniDownloader)",
    pathPlaceholder = "Leave empty for default folder",
    chooseFolder = "Choose Folder",
    resetDefault = "Reset to Default",
    pathSaved = "Download path updated",
    pathReset = "Restored to default download path",
    engineSection = "Core Engine",
    updateEngine = "Update Core Extractor",
    updating = "Updating...",
    engineHint = "Fetch latest yt-dlp extraction rules",
    appInfoSection = "App Info",
    appVersion = "Version",

    formatSheetTitle = "Download Options",
    mediaSelection = "Select Item",
    downloadType = "Format Type",
    typeVideo = "Video with Audio",
    typeAudio = "Audio Only (MP3/M4A)",
    resolution = "Resolution",
    audioFormat = "Audio Format",
    startDownload = "Download",
    downloadAll = "Download All",
    gifHint = "Recognized as animated GIF / clip, can be downloaded as MP4",
    typeCover = "Save Cover",
    saveCover = "Save Cover",
    saveCoverSuccess = "Cover saved to gallery",
    coverDescription = "HD original cover art, saved to gallery directly",
    downloadSingleMode = "Single",
    downloadCollectionMode = "Collection",
    selectAll = "Select All",
    deselectAll = "Deselect",
    invertSelection = "Invert",
    selectedEpisodesCount = "Selected %d / %d",
    downloadSelected = "Download Selected",
    pleaseSelectEpisode = "Please select at least one video",

    tabVideo = "Video",
    tabVideoSub = "HD + Audio",
    tabMute = "Mute",
    tabMuteSub = "Video only",
    tabAudio = "Audio",
    tabAudioSub = "MP3 / M4A",
    tabGif = "GIF",
    tabGifSub = "Looping",

    attachedCoverTitle = "Add-on: HD Cover Image",
    attachedCoverDesc = "Save original high-resolution cover directly to gallery",
    saveCoverAction = "Save Cover",

    selectResolutionWithAudio = "Select video resolution (auto-merge best audio)",
    selectResolutionMute = "Select muted video resolution (no audio stream)",
    selectAudioFormat = "Select audio export format",
    gifEngineTitle = "High-Fidelity GIF Conversion",
    gifEngineDesc = "• Built-in FFmpeg 2-Pass palette engine for vivid colors and compact file size\n• Standard .gif format compatible with photo galleries and messaging apps\n• Switch back to 'Video' anytime to download as MP4",
    switchMultiVideoPrompt = "Tap to switch preview and download video:",
    switchBilibiliPartPrompt = "Tap to switch Bilibili episode / part:",
    videoPartLabel = "Video %d",
    batchDownloadAudio = "Download Selected Audio (%d tracks · %s)",
    batchDownloadGif = "Download Selected GIFs (%d items)",
    batchDownloadVideos = "Download Selected Episodes (%d items · %s)",
    downloadAllCount = "Download All (%d items)",
    switchToCollectionMode = "Switch to Collection Download (%d items)",

    engineStatusTitle = "Core Engine Status",
    engineStatusRunning = "Running",
    engineStatusNotReady = "Not Ready",
    storageCleanTitle = "Storage & Cache Cleanup",
    cleanCacheAction = "Clear Cache & Temporary Files",
    cleanCacheSuccess = "Cache cleared and storage freed",
    customBadge = "Custom",
    changeFolderDialogTitle = "Change Download Directory",
    changeFolderDialogHint = "Select preset or open system file picker:",
    selectViaFilePicker = "Pick Folder in File Manager",
    commonFolders = "Presets:",
    folderDefault = "Default",
    folderMovies = "Movies",
    folderMusic = "Music",
    pathInputLabel = "Absolute Storage Path",
    saveSettings = "Save Settings",

    statusPending = "Pending",
    statusDownloading = "Downloading",
    statusProcessing = "Processing",
    statusCompleted = "Completed",
    statusFailed = "Failed",
    statusCancelled = "Cancelled",
    badgeVideo = "Video",
    badgeMute = "Mute",
    badgeAudio = "Audio",
    badgeGif = "GIF",
    badgeCover = "Cover"
)

val JaStrings = AppStrings(
    navHome = "ホーム",
    navTasks = "タスク",
    navSettings = "設定",

    appSubtitle = "Bilibili、TikTok、X、YouTubeなど主要10大プラットフォーム対応",
    inputPlaceholder = "リンクまたは共有テキストを貼り付け...",
    clear = "クリア",
    paste = "貼り付け",
    pasteClipboard = "クリップボード貼付",
    startAnalyze = "解析開始",
    analyzing = "解析中...",
    activeTasksTitle = "ダウンロード中のタスク",
    viewAll = "すべて見る",
    analyzeFailedTitle = "解析に失敗しました",
    proxyTip = "ヒント: YouTubeやXなどの解析にはプロキシが必要な場合があります。設定画面で構成可能です。",
    copyErrorLog = "エラーログをコピー",
    errorLogCopied = "エラーログをコピーしました",
    setProxy = "プロキシ設定",

    tasksTitle = "ダウンロード管理",
    tabDownloading = "ダウンロード中",
    tabCompleted = "完了",
    emptyDownloading = "進行中のダウンロードはありません",
    emptyCompleted = "完了したダウンロードはありません",
    clearCompleted = "履歴を消去",
    openFolder = "フォルダを開く",
    play = "再生",
    retry = "再試行",
    delete = "削除",
    cancel = "キャンセル",

    settingsTitle = "環境設定",
    languageSection = "言語 (Language)",
    languageZhCn = "简体中文",
    languageZhTw = "繁體中文",
    languageEn = "English",
    languageJa = "日本語",
    proxySection = "ネットワークプロキシ",
    proxyHint = "HTTP / SOCKS5 プロキシに対応",
    proxyPlaceholder = "",
    applyProxy = "保存して適用",
    clearProxy = "プロキシをクリア",
    proxySaved = "プロキシを更新しました",
    proxyCleared = "プロキシをクリアしました",
    storageSection = "保存先フォルダ",
    customPathHint = "カスタム保存先:",
    defaultPath = "デフォルト (Download/OmniDownloader)",
    pathPlaceholder = "空白でデフォルトフォルダに戻す",
    chooseFolder = "フォルダを選択",
    resetDefault = "デフォルトに戻す",
    pathSaved = "保存先を更新しました",
    pathReset = "デフォルト保存先に戻しました",
    engineSection = "コアエンジン",
    updateEngine = "オンラインでコア更新",
    updating = "更新中...",
    engineHint = "最新の yt-dlp 解析ルールを取得",
    appInfoSection = "アプリ情報",
    appVersion = "バージョン",

    formatSheetTitle = "ダウンロード構成",
    mediaSelection = "メディアを選択",
    downloadType = "ダウンロード形式",
    typeVideo = "動画（音声付き）",
    typeAudio = "音声のみ (MP3/M4A)",
    resolution = "動画解像度",
    audioFormat = "音声形式",
    startDownload = "ダウンロード",
    downloadAll = "すべてダウンロード",
    gifHint = "GIFアニメーションとして認識されました。高画質動画として保存できます",
    typeCover = "カバー保存",
    saveCover = "カバー保存",
    saveCoverSuccess = "カバー画像をアルバムに保存しました",
    coverDescription = "高画質な元画像カバーを直接アルバムに保存",
    downloadSingleMode = "単一動画",
    downloadCollectionMode = "合集保存",
    selectAll = "すべて選択",
    deselectAll = "選択解除",
    invertSelection = "反転",
    selectedEpisodesCount = "選択中 %d / %d",
    downloadSelected = "選択分を保存",
    pleaseSelectEpisode = "動画を1つ以上選択してください",

    tabVideo = "動画",
    tabVideoSub = "高画質・音声",
    tabMute = "消音",
    tabMuteSub = "映像のみ",
    tabAudio = "音声抽出",
    tabAudioSub = "MP3 / M4A",
    tabGif = "GIF",
    tabGifSub = "アニメ",

    attachedCoverTitle = "追加オプション: カバー画像",
    attachedCoverDesc = "高画質な元画像カバーを直接写真アルバムに保存",
    saveCoverAction = "保存する",

    selectResolutionWithAudio = "動画解像度を選択 (音声を自動合成)",
    selectResolutionMute = "映像解像度を選択 (音声なし素材)",
    selectAudioFormat = "出力音声形式を選択",
    gifEngineTitle = "高画質 GIF アニメ変換",
    gifEngineDesc = "• 高度なFFmpegパレットエンジンにより鮮明な色合いと軽量サイズを実現\n• 標準.gif形式で保存され、写真アプリ等で再生可能\n• MP4動画として保存したい場合はいつでも「動画」に切り替え可能",
    switchMultiVideoPrompt = "プレビュー・保存する動画を選択:",
    switchBilibiliPartPrompt = "プレビュー・保存するパートを選択:",
    videoPartLabel = "動画 %d",
    batchDownloadAudio = "選択した音声を保存 (%d曲 · %s)",
    batchDownloadGif = "選択したGIFを保存 (%d件)",
    batchDownloadVideos = "選択した合集を保存 (%d本 · %s)",
    downloadAllCount = "すべてダウンロード (%d本)",
    switchToCollectionMode = "合集一括ダウンロードに切り替え (%d本)",

    engineStatusTitle = "コアエンジン状態",
    engineStatusRunning = "稼働中",
    engineStatusNotReady = "未準備",
    storageCleanTitle = "ストレージとキャッシュのクリーンアップ",
    cleanCacheAction = "キャッシュと一時ファイルを消去",
    cleanCacheSuccess = "キャッシュを消去し空き容量を確保しました",
    customBadge = "カスタム",
    changeFolderDialogTitle = "ダウンロード保存先を変更",
    changeFolderDialogHint = "プリセットまたはファイル選択機能を使用:",
    selectViaFilePicker = "ファイル管理アプリでフォルダを選択",
    commonFolders = "プリセット:",
    folderDefault = "デフォルト",
    folderMovies = "動画フォルダ",
    folderMusic = "音楽フォルダ",
    pathInputLabel = "絶対パス",
    saveSettings = "設定を保存",

    statusPending = "待機中",
    statusDownloading = "ダウンロード中",
    statusProcessing = "処理中",
    statusCompleted = "完了",
    statusFailed = "失敗",
    statusCancelled = "キャンセル済",
    badgeVideo = "動画",
    badgeMute = "映像",
    badgeAudio = "音声",
    badgeGif = "GIF",
    badgeCover = "カバー"
)

fun resolveAppStrings(languagePreference: String): AppStrings {
    return when (languagePreference) {
        "zh-CN" -> ZhHansStrings
        "zh-TW" -> ZhHantStrings
        "en" -> EnStrings
        "ja" -> JaStrings
        else -> {
            // "system"
            val defaultLocale = Locale.getDefault()
            val lang = defaultLocale.language.lowercase()
            val country = defaultLocale.country.uppercase()
            val script = defaultLocale.script.lowercase()

            when {
                lang == "zh" && (country == "TW" || country == "HK" || country == "MO" || script.contains("hant")) -> ZhHantStrings
                lang == "zh" -> ZhHansStrings
                lang == "ja" -> JaStrings
                lang == "en" -> EnStrings
                else -> ZhHansStrings
            }
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf { ZhHansStrings }
