import Foundation

/// 国际化文案常列表 (全中文支持)
public struct AppStrings {
    public static var current = AppStrings()
    
    // MARK: - 通用
    public let appName = "OmniDownloader"
    public let confirm = "确定"
    public let cancel = "取消"
    public let delete = "删除"
    public let retry = "重试"
    public let play = "播放"
    public let share = "分享"
    public let save = "保存"
    public let copy = "复制"
    public let success = "成功"
    public let failed = "失败"
    public let errorTitle = "提示"
    public let unknownError = "发生未知错误"
    
    // MARK: - Tab 标签栏
    public let tabHome = "解析"
    public let tabTasks = "下载"
    public let tabSettings = "设置"
    
    // MARK: - 首页 Home
    public let homeTitle = "OmniDownloader"
    public let homeSubtitle = "全网高清原画 · 原生直连极速下载"
    public let inputPrompt = "音视频链接"
    public let inputPlaceholder = "粘贴或输入视频/合集链接 (支持 B站/抖音/快手/小红书等)..."
    public let clearAction = "清空"
    public let pasteAction = "粘贴"
    public let parseAction = "立即解析"
    public let parsing = "正在解析中..."
    public let analyzingPrompt = "正在深度探测音视频流信息..."
    public let clipboardDetectedTitle = "检测到剪贴板链接"
    public let quickDownload = "直接下载"
    public let pasteAndParse = "粘贴解析"
    public let supportedSites = "支持的媒体平台"
    public let tipsTitle = "温馨小贴士"
    public let tipsContent = "1. B站支持 4K、1080P60 帧、DASH 分离流以及分P/UGC合集一键聚合下载。\n2. 抖音、快手、小红书均支持无水印原生高清原画直连提取。\n3. 下载并合成后的视频可自动存入系统《照片》相册中的专属相簿，方便随时查看与分享。"
    
    // MARK: - 弹窗与格式选择
    public let downloadSingleMode = "下载单集"
    public let downloadCollectionMode = "下载合集"
    public let switchBilibiliPartPrompt = "切换分P："
    public let switchMultiVideoPrompt = "切换子视频："
    public let videoPartLabel = "第%d集"
    public let selectAll = "全选"
    public let invertSelection = "反选"
    public let deselectAll = "取消全选"
    public let selectedEpisodesCount = "已选 %d / %d 集"
    public let pleaseSelectEpisode = "请勾选至少一个分集"
    public let downloadType = "下载模式"
    public let saveCover = "保存封面"
    public let badgeCover = "封面"
    public let tabVideo = "音画合流"
    public let tabMute = "纯画面"
    public let tabAudio = "提取音频"
    public let tabGif = "动态图"
    public let selectResolutionWithAudio = "选择视频分辨率 (自动合成最佳声音)"
    public let selectResolutionMute = "选择视频画面分辨率 (无声音)"
    public let selectAudioFormat = "选择音频格式 (无损原轨或通用格式)"
    public let startDownload = "开始下载"
    public let batchDownloadVideos = "批量下载 %d 个视频 (%@)"
    public let batchDownloadAudio = "批量下载 %d 个音频 (%@)"
    public let batchDownloadGif = "批量下载 %d 个动图"
    public let downloadAllCount = "下载全部 (%d个视频)"
    public let switchToCollectionMode = "批量下载全部分集 (%d集)"
    
    // MARK: - 任务管理 Tasks
    public let title = "下载管理"
    public let tasksTitle = "下载管理"
    public let tabAll = "全部"
    public let tabDownloading = "正在下载"
    public let tabCompleted = "已完成"
    public let emptyDownloading = "暂无正在下载的任务"
    public let emptyCompleted = "暂无已完成的任务"
    public let emptyTasks = "暂无下载任务"
    public let emptyTasksSub = "在首页解析视频后即可开始下载"
    public let pauseAll = "全部暂停"
    public let resumeAll = "全部继续"
    public let clearAll = "清空已完成"
    public let clearAllConfirmTitle = "清空确认"
    public let clearAllConfirmMessage = "确定要清空所有已下载完成的历史记录吗？（相册中的视频不会被删除）"
    public let actionDelete = "删除任务"
    public let actionRetry = "重试任务"
    
    // 任务状态文案
    public let statusPending = "等待下载"
    public let statusDownloading = "正在下载"
    public let statusPaused = "已暂停"
    public let statusMuxing = "正在无损合并音视频..."
    public let statusSavingToAlbum = "正在存入系统相册..."
    public let statusCompleted = "下载完成"
    public let statusFailed = "下载失败"
    public let statusSavedToAlbum = "已保存至系统《照片》相册"
    
    // 合集文案
    public let collectionBadge = "合集 · %d 集"
    public let collectionOverallProgress = "总进度：已完成 %d/%d 集 (%d%%)"
    public let currentSubTaskDownloading = "正在下载 (第%d/%d集)：%@"
    public let viewEpisodeDetails = "查看分集详情 (已完成 %d/%d)"
    public let hideEpisodeDetails = "收起分集详情"
    public let playFirstEpisode = "播放首集"
    public let saveToAlbum = "存入相册"
    public let savedToAlbumSuccess = "已成功存入系统《照片》相册"
    public let openInFiles = "在文件App中查看"
    
    // MARK: - 设置 Settings
    public let settingsTitle = "设置"
    public let bilibiliSection = "哔哩哔哩账号登录 (Cookie / SESSDATA)"
    public let bilibiliLoginDesc = "登录后免费解锁 B 站 1080P 高清、1080P60 帧及 4K 超清画质。未登录状态官方最高限制 480P。"
    public let bilibiliLoggedIn = "✓ 已登录 B 站账户"
    public let bilibiliNotLoggedIn = "当前为未登录游客状态 (最高限制 480P)"
    public let bilibiliAutoLoginBtn = "一键安全网页登录"
    public let bilibiliLogout = "退出登录"
    public let downloadSettingsSection = "下载与存储"
    public let autoSaveToAlbum = "自动存入系统《照片》相册"
    public let autoSaveToAlbumDesc = "下载并合成完成的视频或提取的音频封面将自动存入系统相册专属的“OmniDownloader”相簿。"
    public let clearCache = "清理临时缓存文件"
    public let clearCacheSuccess = "临时缓存已成功清理"
    public let about = "关于 OmniDownloader"
    public let version = "版本 v1.0.0 (Build 1)"
    public let openSourceInfo = "基于 SwiftUI + AVFoundation 纯原生构建，原生支持 Bilibili DASH 硬件极速混流。"
}
